version: "1"

services:
  main-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - main-db:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    ports:
      - 5672:5672
    expose:
      - "5672"
      - "15672"
volumes:
  main-db:
